#include "html.h"

const char *const html =
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, "
    "initial-scale=1.0\" /><title>Контроль мікроклімату</title><link rel=\"icon\" "
    "href=\"data:image/png;base64,iVBORw0KGgo=\" /><style> .wrapper { margin-top: 10vh; display: flex; "
    "justify-content: center; align-items: center; width: 100%; } .datalist-container { width: 300px; } .datalist-item "
    "{ display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; } .label { "
    "font-weight: bold; } .countdown { text-align: center; margin-top: 12px; } </style></head><body><div "
    "class=\"wrapper\"><div class=\"datalist-container\"><div class=\"datalist-item\"><span "
    "class=\"label\">Температура</span><span id=\"t\" class=\"value\">...</span></div><div "
    "class=\"datalist-item\"><span class=\"label\">Вологість</span><span id=\"h\" class=\"value\">...</span></div><div "
    "class=\"datalist-item\"><span class=\"label\">Освітленість</span><span id=\"l\" "
    "class=\"value\">...</span></div><div id=\"countdown\" class=\"countdown\">Секунд до оновлення: "
    "10</div></div></div><script> let secondsLeft = 10; let interval = null; async function updateSensorData() { const "
    "{ th: { t, h }, l, } = await (await fetch(\"/api\")).json(); document.getElementById(\"t\").innerHTML = `${t}°C`; "
    "document.getElementById(\"h\").innerHTML = `${h}%`; document.getElementById(\"l\").innerHTML = `${l}/4095`; } "
    "async function handleTimer() { secondsLeft--; const timerElement = document.getElementById(\"countdown\"); "
    "timerElement.innerHTML = `Секунд до оновлення: ${secondsLeft}`; if (secondsLeft <= 0) { clearInterval(interval); "
    "timerElement.innerHTML = `Оновлення...`; await updateSensorData(); secondsLeft = 10; interval = "
    "setInterval(handleTimer, 1000); } } document.addEventListener(\"DOMContentLoaded\", () => { setTimeout(async () "
    "=> { await updateSensorData(); interval = setInterval(handleTimer, 1000); }, 1000); }); </script></body></html>";