#include "html.h"

const char *const htmlTemplate =
    "<!DOCTYPE html><html><head><meta charset=\"UTF-8\" /><meta name=\"viewport\" content=\"width=device-width, "
    "initial-scale=1.0\" /><title>Контроль мікроклімату</title><link rel=\"icon\" "
    "href=\"data:image/png;base64,iVBORw0KGgo=\" /><style> .item { display: flex; justify-content: space-between; "
    "padding: 8px 0; border-bottom: 1px solid #eee; } .value { display: flex; } </style></head><body><div "
    "style=\"margin-top: 10vh; display: flex; justify-content: center; align-items: center; width: 100%%\"><div "
    "style=\"width: 300px\"><div class=\"item\"><strong>Температура</strong><div class=\"value\"><div "
    "id=\"t\">%d</div> °C </div></div><div class=\"item\"><strong>Вологість</strong><div class=\"value\"><div "
    "id=\"h\">%d</div> %% </div></div><div class=\"item\"><strong>Освітленість</strong><div class=\"value\"><div "
    "id=\"l\"></div> lx </div></div><div id=\"ct\" style=\"text-align: center; margin-top: "
    "12px\"></div></div></div><script> const lElement = document.getElementById(\"l\"); lElement.innerHTML = "
    "getLuxNumber(%lu).toString(); let secondsLeft = 10; function getLuxNumber(luminosity) { return luminosity; } "
    "async function update() { const { th: { t, h }, l, } = await (await fetch(\"/api\")).json(); "
    "document.getElementById(\"t\").innerHTML = t.toString(); document.getElementById(\"h\").innerHTML = h.toString(); "
    "lElement.innerHTML = getLuxNumber(l).toString(); } async function handleTimer() { secondsLeft--; const element = "
    "document.getElementById(\"ct\"); element.innerHTML = `Оновлення через: ${secondsLeft}`; if (secondsLeft <= 0) { "
    "clearInterval(interval); element.innerHTML = `Оновлення...`; await update(); secondsLeft = 10; element.innerHTML "
    "= `Оновлення через: ${secondsLeft}`; interval = setInterval(handleTimer, 1000); } } let interval = "
    "setInterval(handleTimer, 1000); </script></body></html>";